### ISSUE TITLE
Assignment3

### ISSUE THREAD

**Issue by AndreyIsakov01** [Andrew82mm/HomeAssignment#3]
Ошибка при сборке тестов
`vboxuser@ubuntu:~/CPP/HomeAssignment/HomeAssignment3$ make test` <br />
`g++ -std=c++11 -Wall -Wextra -c AutobotTest.cpp -o AutobotTest.o` <br />
`In file included from /usr/include/gtest/gtest-message.h:57, `<br />
`                 from /usr/include/gtest/gtest-assertion-result.h:46,` <br />
`                 from /usr/include/gtest/gtest.h:64,` <br />
`                 from AutobotTest.cpp:1:` <br />
`/usr/include/gtest/internal/gtest-port.h:279:2: error: #error C++ versions less than C++14 are not supported.` <br />
`  279 | #error C++ versions less than C++14 are not supported.` <br />
 `     |  ^~~~~`

**Comment by Andrew82mm** [comment]
Fixed
